# Generated by Django 4.0 on 2023-11-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touroku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopost',
            name='subtitle',
            field=models.CharField(max_length=40, null=True, verbose_name='サブタイトル'),
        ),
    ]
